service: another-service # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.7
  versionFunctions: false # tells aws lambda not to store multiple versions of function
  memorySize: 128
  stage: dev
  region: us-west-2 # cheaper and has more bells and whistles
  apiName: do-stuff-api-name-${self:provider.stage}
  profile: serverless-test

functions:
  weather:
    handler: handler.weather
    layers:
      - arn:aws:lambda:us-west-2:064892837453:layer:jwtLib:4
    environment:
      APIXU_WEATHER_API_KEY: ${file(./serverless.env.yml) :APIXU_WEATHER_API_KEY}
    events:
      - http:
          path: /forecast
          method: get

  jwt:
    handler: handler.jwt
    layers:
      - arn:aws:lambda:us-west-2:064892837453:layer:jwtLib:4
    events:
      - http:
          path: /jwt
          method: get

plugins:
  - serverless-python-requirements
