service: practice-serverless # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.7
  versionFunctions: false # tells aws lambda not to store multiple versions of function
  memorySize: 128
  stage: dev
  region: us-west-2 # cheaper and has more bells and whistles
  apiName: my-custom-api-name-${self:provider.stage}
  profile: serverless-test

custom:
  wsgi:
    app: foo.run.app
    packRequirements: false

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get

  flask:
    handler: wsgi_handler.handler
    events:
      - http: 'ANY {proxy+}'

plugins:
  - serverless-python-requirements
  - serverless-wsgi
